# Generated by Django 4.2.7 on 2026-06-05 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_booklist_booklistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('max_borrow_days', models.PositiveIntegerField(default=30, verbose_name='最大借阅天数')),
                ('max_borrow_quantity', models.PositiveIntegerField(default=0, help_text='0表示无限制', verbose_name='每人最大同时借阅数量')),
                ('max_daily_requests', models.PositiveIntegerField(default=0, help_text='0表示无限制', verbose_name='每日最大申请次数')),
                ('allow_renew', models.BooleanField(default=True, verbose_name='是否允许续借')),
                ('max_renew_count', models.PositiveIntegerField(default=1, verbose_name='最大续借次数')),
                ('renew_days', models.PositiveIntegerField(default=15, verbose_name='续借天数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '借阅规则',
                'verbose_name_plural': '借阅规则',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_user_book_active_reservation',
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='borrow_rule_snapshot',
            field=models.TextField(default='{}', verbose_name='借阅规则快照'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='renew_count',
            field=models.PositiveIntegerField(default=0, verbose_name='续借次数'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'book', 'status')},
        ),
    ]
